DROP TABLE if EXISTS customer;
DROP TABLE if EXISTS vehicle;
DROP TABLE if EXISTS leasing_contract;

CREATE TABLE customer (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) DEFAULT NULL,
    birthdate DATE NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 AUTO_INCREMENT = 5;

CREATE TABLE vehicle (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    model_year VARCHAR(4) NOT NULL,
    vin VARCHAR(50) DEFAULT NULL,
    price DECIMAL(15, 2) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 AUTO_INCREMENT = 5;

CREATE TABLE leasing_contract (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    customer_id BIGINT(20) NOT NULL,
    vehicle_id BIGINT(20) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    contract_number BIGINT UNIQUE NOT NULL,
    monthly_rate DECIMAL(15, 2),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 AUTO_INCREMENT = 5;
